### ISSUE TITLE
4 Functions

### ISSUE THREAD

**Issue by ytz** [UBC-MDS/covizpy#1] opened 2022-01-12 07:01 UTC
Hi all, we can use this issue to state which functions you would like to implement. Feel free to edit the table below:

| Name   | Function |
|--------|----------|
| Rohit      |  Create a line chart presenting COVID total new cases verses another metric within a time period |
| Rong      | Create a line chart presenting specific country/countries COVID information within a time period |
| Thomas | Get Covid data as pandas dataframe based on date range and location provided |
| TZ          | Summary plotting function for categorical variables within a date range         |

**Comment by rrrohit1** [comment] 2022-01-13 15:27
I tried to plot monthly new cases VS positivity rate to see any relationship between the two.

Also, fairly simple to download data.
`covid_df = pd.read_csv('https://covid.ourworldindata.org/data/owid-covid-data.csv')`

![image](https://user-images.githubusercontent.com/52863845/149358332-4fb0e93a-9185-4022-98c1-41674a6c69d8.png)

**Comment by ytz** [comment] 2022-01-13 22:12
I was thinking of making a simple function to output a summary plot by countries or other categorical factors by a date range, like this:
![Screen Shot 2022-01-13 at 2 11 43 PM](https://user-images.githubusercontent.com/1884616/149417161-f91362d6-49c2-4811-b9cd-e2cbbd688ce9.png)

**Comment by thomassiu** [comment] 2022-01-13 23:36
Hi all, 

Sorry that I was engaged with some other stuff this week and I will catch up the work tonight and tomorrow morning. Meanwhile, for my function, I would like to create one which returns contents as a json format based on the options chosen.
For example, we can input (country, 7-day-rolling, date) and it returns the average confirmed cases in past 7 days. I will try to put some meaningful statistics there - that aims for developers to easily access summarized data.

**Comment by lirnish** [comment] 2022-01-14 01:00
Hi all,
I think since we have a summarized plot, summarized data grid, I can do a specific separate-by-country trend plot (maybe include death rate, etc.)
Or do we still need a function to download the data? I could do that too (or maybe include it as a sub-function as it is just one line?)

**Comment by thomassiu** [comment] 2022-01-14 01:18
Believe we don't need a specific function to download - I can embed the data download into my function .
For other functions we can do a simple check if the file exists in local drive. Does that sound good?

**Comment by rrrohit1** [comment] 2022-01-14 01:19
@thomassiu Sounds good.

I will open 4 separate issues for each function (required for Milestone 1; @thomassiu you will need to assign one person to each of the above issues in the project board) and we can discuss the functions there. Also, please create a branch tonight for yourself and then work on it and update the repo through that branch. Don't work on the main branch directly.

**Comment by lirnish** [comment] 2022-01-14 01:34
Given that the file is updating, I feel like we should always re-download the data, so all the functions should embed the data download I believe.

**Comment by lirnish** [comment] 2022-01-14 02:02
Wondering if we could share the name of our function now so we are on the same page? I am thinking of mine as `plotspec`, does that sounds ok? And btw, are we all going to use Altair for python to do the plotting?

**Comment by ytz** [comment] 2022-01-14 04:29
We can perhaps try using `_` to separate words in function, as suggested in PEP 8

> Function names should be lowercase, with words separated by underscores as necessary to improve readability.

I guess my function could be `plot_summary` or something

**Comment by thomassiu** [comment] 2022-01-14 16:47
Due to the constraints of the four functions only, I will change my function to only return a df of the downloaded data. I think we can't even write a class too? If yes, then at least I can put the df download into the class while it's being initialized....

**Comment by thomassiu** [comment] 2022-01-15 17:01
Closed the issue as the spec of all functions are merged.

**Closed as completed by thomassiu** 2022-01-15 17:01 UTC
